name: Run Python Script from specific branch

on: [push]

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout `Customer-Intelligence-Engine-Gaussian-distribution-with-IQR-and-Bayesian-style-KDE` branch
        uses: actions/checkout@v3
        with:
          ref: Customer-Intelligence-Engine-Gaussian-distribution-with-IQR-and-Bayesian-style-KDE

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pymc3
        
      - name: Install dependencies
        run: |
          if test -f requirements.txt; then pip install -r requirements.txt; fi

      - name: Run segmentation script
        run: python src/Customer-Intelligence-GP.py

      - name: Commit and push outputs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add outputs/*.png outputs/*.csv
          git commit -m "Add generated plots and CSV [auto]" || echo "No changes to commit"
          git push origin add-pca-visualization
